const ideasData = [
    // SPATIAL COMPUTING (11 ideas)
    {
        id: 1,
        name: "Spatial Memory Palace",
        icon: "🏛️",
        category: "spatial",
        oneLiner: "Transform any physical space into a 3D memory palace where you attach persistent AR knowledge anchors that survive across sessions, creating spatially-indexed learning systems.",
        price: "$49.99",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "STRONG GO",
        file: "01-spatial-computing/001-spatial-memory-palace.md"
    },
    {
        id: 2,
        name: "Acoustic Room Analyzer Pro",
        icon: "🔊",
        category: "spatial",
        oneLiner: "Professional acoustic analysis suite that maps room resonance, identifies reflection points, calculates RT60 decay times, and generates scientifically-grounded treatment recommendations with AR placement guides.",
        price: "$79.99",
        complexity: "High",
        timeline: "16-22 weeks",
        verdict: "STRONG GO",
        file: "01-spatial-computing/002-acoustic-room-analyzer.md"
    },
    {
        id: 3,
        name: "Motion Signature Authenticator",
        icon: "🔐",
        category: "spatial",
        oneLiner: "Behavioral biometric security using your unique movement signature—how you pick up, hold, type, and interact with your phone creates an unforgeable continuous authentication layer.",
        price: "$29.99",
        complexity: "High",
        timeline: "18-24 weeks",
        verdict: "GO",
        file: "01-spatial-computing/003-motion-signature-authenticator.md"
    },
    {
        id: 4,
        name: "Environmental Intelligence Hub",
        icon: "🌍",
        category: "spatial",
        oneLiner: "Transform your phone into a comprehensive environmental sensing station that correlates air pressure changes, electromagnetic fields, light quality, and atmospheric conditions with your health and productivity data.",
        price: "$39.99",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "GO",
        file: "01-spatial-computing/004-environmental-intelligence-hub.md"
    },
    {
        id: 5,
        name: "Reality Anchor Network",
        icon: "📍",
        category: "spatial",
        oneLiner: "Create persistent, discoverable AR annotations in the physical world that others can find and interact with—a global layer of shared spatial information for location-based knowledge, art, and communication.",
        price: "$59.99",
        complexity: "High",
        timeline: "20-28 weeks",
        verdict: "CONDITIONAL GO",
        file: "01-spatial-computing/005-reality-anchor-network.md"
    },
    {
        id: 6,
        name: "Structural Vibration Monitor Pro",
        icon: "📊",
        category: "spatial",
        oneLiner: "Engineering-grade structural vibration analysis that detects building resonance, machinery imbalance, bridge oscillations, and early warning signs of structural fatigue using phone accelerometers with professional reporting.",
        price: "$89.99",
        complexity: "High",
        timeline: "16-20 weeks",
        verdict: "GO",
        file: "01-spatial-computing/006-structural-vibration-monitor.md"
    },
    {
        id: 7,
        name: "Precision Pose Analyzer",
        icon: "🤸",
        category: "spatial",
        oneLiner: "Biomechanical analysis system that uses computer vision to measure joint angles, detect movement asymmetries, track rehabilitation progress, and generate clinical-grade posture reports with real-time corrective feedback.",
        price: "$49.99",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "STRONG GO",
        file: "01-spatial-computing/007-precision-pose-analyzer.md"
    },
    {
        id: 8,
        name: "Magnetic Field Mapper",
        icon: "🧲",
        category: "spatial",
        oneLiner: "Create detailed 3D magnetic field maps of indoor spaces to locate hidden wiring, detect EMI sources, verify shielded room integrity, and find buried metal objects with professional visualization and reporting.",
        price: "$34.99",
        complexity: "High",
        timeline: "12-16 weeks",
        verdict: "GO",
        file: "01-spatial-computing/008-magnetic-field-mapper.md"
    },
    {
        id: 9,
        name: "Light Quality Profiler Pro",
        icon: "💡",
        category: "spatial",
        oneLiner: "Professional lighting analysis that measures illuminance, color temperature, CRI, flicker, and circadian impact using advanced camera spectral analysis—replacing $500+ light meters for photographers, designers, and wellness professionals.",
        price: "$29.99",
        complexity: "High",
        timeline: "12-16 weeks",
        verdict: "GO",
        file: "01-spatial-computing/009-light-quality-profiler.md"
    },
    {
        id: 10,
        name: "Terrain Analyzer Pro",
        icon: "🏔️",
        category: "spatial",
        oneLiner: "Professional terrain surveying app that uses LiDAR to capture topographic models, calculate slopes, volumes, and drainage patterns, and generate construction-ready site plans—replacing survey equipment for preliminary assessments.",
        price: "$69.99",
        complexity: "High",
        timeline: "18-24 weeks",
        verdict: "GO",
        file: "01-spatial-computing/010-terrain-analyzer-pro.md"
    },
    {
        id: 11,
        name: "Acoustic Positioning System",
        icon: "📡",
        category: "spatial",
        oneLiner: "Sub-centimeter indoor positioning using phone speakers and microphones to create an acoustic radar system—enabling precise location tracking in warehouses, retail, museums, and any space where GPS fails.",
        price: "$49.99",
        complexity: "High",
        timeline: "20-26 weeks",
        verdict: "CONDITIONAL GO",
        file: "01-spatial-computing/011-acoustic-positioning-system.md"
    },
    
    // COGNITIVE WELLNESS (11 ideas)
    {
        id: 12,
        name: "Neural State Tracker",
        icon: "🧠",
        category: "cognitive",
        oneLiner: "A comprehensive cognitive state monitoring system that uses phone sensors to measure heart rate variability, voice stress patterns, and micro-movement analysis to provide real-time awareness of your mental state and intervention suggestions.",
        price: "$39.99/year",
        complexity: "High",
        timeline: "18-24 weeks",
        verdict: "GO",
        file: "02-cognitive-wellness/012-neural-state-tracker.md"
    },
    {
        id: 13,
        name: "Cognitive Load Manager",
        icon: "⚡",
        category: "cognitive",
        oneLiner: "An intelligent system that measures your cognitive load in real-time based on context switching, information input rate, and task complexity—then actively protects your mental bandwidth by filtering, batching, and scheduling demands.",
        price: "$29.99",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "STRONG GO",
        file: "02-cognitive-wellness/013-cognitive-load-manager.md"
    },
    {
        id: 14,
        name: "Therapeutic Voice Journal",
        icon: "🎙️",
        category: "cognitive",
        oneLiner: "An AI-powered voice journaling system that uses therapeutic frameworks (CBT, ACT, IFS) to guide reflection, automatically detects cognitive distortions, tracks emotional patterns, and provides personalized insights—like having a therapist in your pocket.",
        price: "$24.99/year",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "STRONG GO",
        file: "02-cognitive-wellness/014-therapeutic-voice-journal.md"
    },
    {
        id: 15,
        name: "Attention Recovery Protocol",
        icon: "🎯",
        category: "cognitive",
        oneLiner: "A scientifically-designed attention rehabilitation program that uses progressive training, environmental design, and real-time interventions to restore your capacity for deep focus—rebuilding attention span that modern technology has eroded.",
        price: "$19.99",
        complexity: "Medium",
        timeline: "12-16 weeks",
        verdict: "GO",
        file: "02-cognitive-wellness/015-attention-recovery-protocol.md"
    },
    {
        id: 16,
        name: "Decision Fatigue Shield",
        icon: "🛡️",
        category: "cognitive",
        oneLiner: "An intelligent decision automation system that learns your preferences, pre-makes routine decisions, and protects your limited daily decision-making capacity for the choices that actually matter.",
        price: "$29.99",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "GO",
        file: "02-cognitive-wellness/016-decision-fatigue-shield.md"
    },
    {
        id: 17,
        name: "Inner Dialogue Coach",
        icon: "💬",
        category: "cognitive",
        oneLiner: "A self-talk transformation system that captures, analyzes, and reshapes your inner dialogue—detecting negative self-talk patterns, measuring your self-compassion ratio, and training you to speak to yourself like your best friend would.",
        price: "$34.99/year",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "GO",
        file: "02-cognitive-wellness/017-inner-dialogue-coach.md"
    },
    {
        id: 18,
        name: "Dream Pattern Analyzer",
        icon: "🌙",
        category: "cognitive",
        oneLiner: "An AI-powered dream journaling system that uses voice capture, symbol analysis, and pattern recognition to reveal recurring themes, emotional processing patterns, and connections between your waking life and dream content.",
        price: "$24.99/year",
        complexity: "Medium",
        timeline: "12-16 weeks",
        verdict: "GO",
        file: "02-cognitive-wellness/018-dream-pattern-analyzer.md"
    },
    {
        id: 19,
        name: "Relationship Intelligence System",
        icon: "💝",
        category: "cognitive",
        oneLiner: "A relationship CRM for your personal life that tracks interaction patterns, surfaces neglected connections, provides conversation intelligence, and helps you be intentional about nurturing the relationships that matter most.",
        price: "$39.99/year",
        complexity: "Medium",
        timeline: "12-16 weeks",
        verdict: "GO",
        file: "02-cognitive-wellness/019-relationship-intelligence.md"
    },
    {
        id: 20,
        name: "Memory Consolidation System",
        icon: "📚",
        category: "cognitive",
        oneLiner: "A neuroscience-based memory enhancement system that uses spaced repetition, sleep-timed review, multi-modal encoding, and retrieval practice to transform experiences, books, and learnings into permanent long-term memories.",
        price: "$44.99",
        complexity: "High",
        timeline: "16-20 weeks",
        verdict: "STRONG GO",
        file: "02-cognitive-wellness/020-memory-consolidation-system.md"
    },
    {
        id: 21,
        name: "Emotional Regulation Trainer",
        icon: "💚",
        category: "cognitive",
        oneLiner: "A DBT-informed emotional regulation training system that detects emotional escalation in real-time using biometric signals and provides in-the-moment intervention guidance to help you respond skillfully rather than react impulsively.",
        price: "$29.99/year",
        complexity: "High",
        timeline: "18-22 weeks",
        verdict: "CONDITIONAL GO",
        file: "02-cognitive-wellness/021-emotional-regulation-trainer.md"
    },
    {
        id: 22,
        name: "Identity Narrative Engine",
        icon: "📖",
        category: "cognitive",
        oneLiner: "A personal mythology system that helps you author, strengthen, and evolve your life narrative—integrating experiences into meaningful stories that build resilience, purpose, and a coherent sense of identity.",
        price: "$49.99",
        complexity: "High",
        timeline: "16-20 weeks",
        verdict: "GO",
        file: "02-cognitive-wellness/022-identity-narrative-engine.md"
    },
    
    // PROFESSIONAL DOMAIN (11 ideas)
    {
        id: 23,
        name: "Clinical Decision Companion",
        icon: "⚕️",
        category: "professional",
        oneLiner: "An evidence-based clinical decision support system for physicians that provides differential diagnosis assistance, drug interaction checking, and guideline-based treatment recommendations—all running locally with complete patient privacy.",
        price: "$99.99/year",
        complexity: "High",
        timeline: "24-32 weeks",
        verdict: "CONDITIONAL GO",
        file: "03-professional-domain/023-clinical-decision-companion.md"
    },
    {
        id: 24,
        name: "Legal Research Assistant",
        icon: "⚖️",
        category: "professional",
        oneLiner: "A comprehensive legal research tool for attorneys that provides case law analysis, statutory interpretation, contract clause extraction, and argument mapping—with complete client confidentiality through fully offline operation.",
        price: "$149.99/year",
        complexity: "High",
        timeline: "24-30 weeks",
        verdict: "GO",
        file: "03-professional-domain/024-legal-research-assistant.md"
    },
    {
        id: 25,
        name: "Construction Superintendent Pro",
        icon: "🏗️",
        category: "professional",
        oneLiner: "An all-in-one construction management system for superintendents that combines daily reports, photo documentation, punch lists, safety checklists, progress tracking, and plan viewing—all working offline on job sites without cellular coverage.",
        price: "$79.99/month",
        complexity: "High",
        timeline: "16-20 weeks",
        verdict: "STRONG GO",
        file: "03-professional-domain/025-construction-superintendent.md"
    },
    {
        id: 26,
        name: "Agricultural Field Scout Pro",
        icon: "🌾",
        category: "professional",
        oneLiner: "An AI-powered crop scouting system that identifies plant diseases, pest damage, and nutrient deficiencies from photos, maps field issues by GPS, generates treatment recommendations, and creates professional agronomist-quality reports.",
        price: "$99.99/year",
        complexity: "High",
        timeline: "20-26 weeks",
        verdict: "STRONG GO",
        file: "03-professional-domain/026-agricultural-field-scout.md"
    },
    {
        id: 27,
        name: "Veterinary Diagnostic Aid",
        icon: "🐾",
        category: "professional",
        oneLiner: "An evidence-based veterinary clinical decision support system providing differential diagnosis, drug dosing by species and weight, toxicology reference, and case documentation—designed for the unique challenges of veterinary medicine across multiple species.",
        price: "$149.99/year",
        complexity: "High",
        timeline: "22-28 weeks",
        verdict: "GO",
        file: "03-professional-domain/027-veterinary-diagnostic-aid.md"
    },
    {
        id: 28,
        name: "Film Production Assistant Pro",
        icon: "🎬",
        category: "professional",
        oneLiner: "A comprehensive film/video production toolkit combining script breakdown, shot planning, continuity tracking, sun position/golden hour calculation, color checker calibration, and production document generation—everything a director or DP needs on set.",
        price: "$79.99",
        complexity: "High",
        timeline: "16-20 weeks",
        verdict: "GO",
        file: "03-professional-domain/028-film-production-assistant.md"
    },
    {
        id: 29,
        name: "Marine Navigation Companion",
        icon: "⚓",
        category: "professional",
        oneLiner: "A comprehensive marine navigation and planning system with offline charts, tidal predictions, weather integration, anchor watch, passage planning, and logbook functionality—designed for coastal cruising and offshore sailing.",
        price: "$89.99",
        complexity: "High",
        timeline: "22-28 weeks",
        verdict: "STRONG GO",
        file: "03-professional-domain/029-marine-navigation-companion.md"
    },
    {
        id: 30,
        name: "Wine Professional Suite",
        icon: "🍷",
        category: "professional",
        oneLiner: "A comprehensive wine professional tool combining cellar inventory management, tasting note analysis, sommelier exam preparation, service temperature tracking, and wine list building—designed for sommeliers, retailers, and serious collectors.",
        price: "$69.99/year",
        complexity: "High",
        timeline: "16-20 weeks",
        verdict: "GO",
        file: "03-professional-domain/030-wine-professional-suite.md"
    },
    {
        id: 31,
        name: "Appraisal Professional Suite",
        icon: "🏠",
        category: "professional",
        oneLiner: "A comprehensive real estate appraisal toolkit with LiDAR floor plan measurement, photo documentation with automatic room labeling, comparable analysis, sketch generation, and USPAP-compliant report generation—everything appraisers need in the field.",
        price: "$149.99/year",
        complexity: "High",
        timeline: "22-28 weeks",
        verdict: "STRONG GO",
        file: "03-professional-domain/031-appraisal-professional.md"
    },
    {
        id: 32,
        name: "Forensic Documentation Pro",
        icon: "🔍",
        category: "professional",
        oneLiner: "A chain-of-custody-compliant evidence documentation system for investigators, insurance adjusters, and legal professionals—combining photo/video capture with automatic metadata, measurement tools, and tamper-proof storage.",
        price: "$199.99/year",
        complexity: "High",
        timeline: "20-26 weeks",
        verdict: "GO",
        file: "03-professional-domain/032-forensic-documentation.md"
    },
    {
        id: 33,
        name: "Auction Catalog Assistant",
        icon: "🔨",
        category: "professional",
        oneLiner: "A specialized tool for auction houses and estate sale professionals combining inventory photography, condition reporting, research assistance, lot numbering, catalog generation, and bidding analytics—streamlining the path from intake to hammer.",
        price: "$99.99/month",
        complexity: "High",
        timeline: "18-22 weeks",
        verdict: "GO",
        file: "03-professional-domain/033-auction-catalog-assistant.md"
    },
    
    // DATA INTELLIGENCE (11 ideas)
    {
        id: 34,
        name: "Personal Data Engine",
        icon: "📊",
        category: "data",
        oneLiner: "A unified personal data warehouse that aggregates health, productivity, location, and behavioral data from all your sources, runs local analytics to discover cross-domain correlations, and surfaces actionable insights about your life patterns.",
        price: "$49.99",
        complexity: "High",
        timeline: "22-28 weeks",
        verdict: "STRONG GO",
        file: "04-data-intelligence/034-personal-data-engine.md"
    },
    {
        id: 35,
        name: "Financial Forensics Lab",
        icon: "💰",
        category: "data",
        oneLiner: "An advanced personal finance analysis tool that imports your transaction history and applies forensic-level analysis to detect spending patterns, subscription leaks, lifestyle creep, and financial behavioral insights that budgeting apps miss.",
        price: "$39.99",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "STRONG GO",
        file: "04-data-intelligence/035-financial-forensics.md"
    },
    {
        id: 36,
        name: "Time Investment Analyzer",
        icon: "⏱️",
        category: "data",
        oneLiner: "A sophisticated time auditing system that tracks how you actually spend time versus how you think you spend it, calculates ROI on different activities, and reveals the true opportunity cost of your daily choices.",
        price: "$29.99",
        complexity: "Medium",
        timeline: "12-16 weeks",
        verdict: "GO",
        file: "04-data-intelligence/036-time-investment-analyzer.md"
    },
    {
        id: 37,
        name: "Conversation Intelligence System",
        icon: "💬",
        category: "data",
        oneLiner: "A personal communication analytics platform that analyzes your conversations (with consent) to reveal speaking patterns, listening ratios, filler word frequency, topic distributions, and provides coaching for more effective interpersonal communication.",
        price: "$49.99/year",
        complexity: "High",
        timeline: "16-20 weeks",
        verdict: "CONDITIONAL GO",
        file: "04-data-intelligence/037-conversation-intelligence.md"
    },
    {
        id: 38,
        name: "Reading Analytics Engine",
        icon: "📚",
        category: "data",
        oneLiner: "A comprehensive reading analytics platform that tracks everything you read (books, articles, documents), measures reading speed and comprehension, identifies your learning patterns, and optimizes your information consumption for maximum retention and application.",
        price: "$24.99",
        complexity: "Medium",
        timeline: "12-16 weeks",
        verdict: "GO",
        file: "04-data-intelligence/038-reading-analytics-engine.md"
    },
    {
        id: 39,
        name: "Habit Correlation Engine",
        icon: "🔗",
        category: "data",
        oneLiner: "An advanced habit analytics system that doesn't just track habits but discovers which habits actually impact your outcomes—revealing the keystone behaviors that create cascading positive effects in your life.",
        price: "$29.99",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "STRONG GO",
        file: "04-data-intelligence/039-habit-correlation-engine.md"
    },
    {
        id: 40,
        name: "Energy Optimization System",
        icon: "⚡",
        category: "data",
        oneLiner: "A personal energy management platform that tracks your physical and mental energy levels throughout the day, identifies patterns and drains, and optimizes your schedule to align high-value work with peak energy states.",
        price: "$39.99/year",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "STRONG GO",
        file: "04-data-intelligence/040-energy-optimization-system.md"
    },
    {
        id: 41,
        name: "Personal Network Analyzer",
        icon: "🕸️",
        category: "data",
        oneLiner: "A sophisticated analysis tool for your personal and professional network that maps relationship strengths, identifies network gaps, surfaces hidden connections, and provides strategic insights for intentional network building.",
        price: "$34.99",
        complexity: "High",
        timeline: "16-20 weeks",
        verdict: "CONDITIONAL GO",
        file: "04-data-intelligence/041-social-network-analyzer.md"
    },
    {
        id: 42,
        name: "Decision Journal System",
        icon: "📋",
        category: "data",
        oneLiner: "A systematic decision tracking and analysis platform that captures your decisions at the moment of making them, tracks outcomes over time, identifies decision-making biases, and helps you calibrate your judgment through evidence.",
        price: "$29.99",
        complexity: "Medium",
        timeline: "12-16 weeks",
        verdict: "GO",
        file: "04-data-intelligence/042-decision-journal-system.md"
    },
    {
        id: 43,
        name: "Personal Knowledge Graph",
        icon: "🧠",
        category: "data",
        oneLiner: "A personal knowledge management system that automatically connects ideas across all your notes, highlights, and captures—building a traversable knowledge graph that surfaces relevant connections when you need them and grows smarter over time.",
        price: "$59.99",
        complexity: "High",
        timeline: "20-26 weeks",
        verdict: "STRONG GO",
        file: "04-data-intelligence/043-personal-knowledge-graph.md"
    },
    {
        id: 44,
        name: "Life Experiment Lab",
        icon: "🔬",
        category: "data",
        oneLiner: "A rigorous personal experimentation platform for running self-experiments with proper controls, randomization, and statistical analysis—turning life optimization from guesswork into science with n=1 trials.",
        price: "$39.99",
        complexity: "High",
        timeline: "14-18 weeks",
        verdict: "STRONG GO",
        file: "04-data-intelligence/044-life-experiment-lab.md"
    }
];
