import { PromptPattern } from './types';

// The 7 core prompt patterns
export const PROMPT_PATTERNS: PromptPattern[] = [
  {
    id: 'role',
    name: 'Role Assignment',
    description: 'Gives the AI a specific persona or expertise to embody',
    indicators: [
      'you are',
      'act as',
      'pretend you are',
      'imagine you are',
      'as a',
      'expert',
      'specialist',
      'professional',
      'consultant',
    ],
    weight: 15,
  },
  {
    id: 'context',
    name: 'Context Setting',
    description: 'Provides background information and situational awareness',
    indicators: [
      'background',
      'context',
      'situation',
      'scenario',
      'given that',
      'considering',
      'in the context of',
      'for the purpose of',
    ],
    weight: 15,
  },
  {
    id: 'task',
    name: 'Clear Task Definition',
    description: 'Explicitly states what action the AI should take',
    indicators: [
      'write',
      'create',
      'generate',
      'explain',
      'analyze',
      'summarize',
      'list',
      'describe',
      'help me',
      'provide',
    ],
    weight: 20,
  },
  {
    id: 'format',
    name: 'Format Specification',
    description: 'Defines the structure and format of the output',
    indicators: [
      'format',
      'structure',
      'bullet points',
      'numbered list',
      'table',
      'headers',
      'sections',
      'paragraphs',
      'words',
      'characters',
    ],
    weight: 10,
  },
  {
    id: 'constraints',
    name: 'Constraints & Boundaries',
    description: 'Sets limitations and what to avoid',
    indicators: [
      'avoid',
      'don\'t',
      'do not',
      'never',
      'limit',
      'only',
      'must not',
      'should not',
      'exclude',
      'without',
    ],
    weight: 10,
  },
  {
    id: 'audience',
    name: 'Audience Targeting',
    description: 'Specifies who the output is for',
    indicators: [
      'for',
      'audience',
      'reader',
      'target',
      'aimed at',
      'intended for',
      'beginners',
      'experts',
      'professionals',
      'students',
    ],
    weight: 10,
  },
  {
    id: 'tone',
    name: 'Tone & Style',
    description: 'Defines the voice and style of communication',
    indicators: [
      'tone',
      'style',
      'voice',
      'formal',
      'informal',
      'friendly',
      'professional',
      'conversational',
      'academic',
      'casual',
    ],
    weight: 10,
  },
];

// Additional patterns that boost quality
export const ADVANCED_PATTERNS: PromptPattern[] = [
  {
    id: 'examples',
    name: 'Example Provision',
    description: 'Includes examples of desired output',
    indicators: [
      'for example',
      'such as',
      'like this',
      'example:',
      'here is an example',
      'similar to',
    ],
    weight: 5,
  },
  {
    id: 'chain_of_thought',
    name: 'Chain of Thought',
    description: 'Encourages step-by-step reasoning',
    indicators: [
      'step by step',
      'think through',
      'walk me through',
      'explain your reasoning',
      'show your work',
      'break down',
    ],
    weight: 5,
  },
];

export const ALL_PATTERNS = [...PROMPT_PATTERNS, ...ADVANCED_PATTERNS];

