from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Idea:
    id: int
    folder: str
    slug: str
    name: str
    category: str
    tier: str
    apis: str
    offline: str
    one_liner: str
    problem: str
    solution: str
    target_user: str
    features: list[str]
    model: str
    price: str
    strategy: str
    viz: str
    primary_apis: list[str]
    offline_strategy: str
    data_handling: str
    competition: str
    edge: str
    complexity: str
    timeline: str
    challenges: str


def render_md(i: Idea) -> str:
    lines: list[str] = []
    lines.append(f"# {i.name}")
    lines.append("")
    lines.append(f"**ID:** {i.id}")
    lines.append(f"**Category:** {i.category}")
    lines.append(f"**Tier:** {i.tier}")
    lines.append(f"**APIs:** {i.apis}")
    lines.append(f"**Offline:** {i.offline}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## One-Liner")
    lines.append("")
    lines.append(i.one_liner)
    lines.append("")
    lines.append("## Problem")
    lines.append("")
    lines.append(i.problem)
    lines.append("")
    lines.append("## Solution")
    lines.append("")
    lines.append(i.solution)
    lines.append("")
    lines.append("## Target User")
    lines.append("")
    lines.append(i.target_user)
    lines.append("")
    lines.append("## Key Features")
    lines.append("")
    for f in i.features:
        lines.append(f"- {f}")
    lines.append("")
    lines.append("## Monetization")
    lines.append("")
    lines.append(f"**Model:** {i.model}")
    lines.append(f"**Price:** {i.price}")
    lines.append(f"**Strategy:** {i.strategy}")
    lines.append("")
    lines.append("## Visualization Concept")
    lines.append("")
    lines.append("```")
    lines.append("┌─────────────────────────────────────┐")
    lines.append("│                                     │")
    viz = i.viz[:33]
    lines.append(f"│     {viz:<33}│")
    lines.append("│                                     │")
    lines.append("└─────────────────────────────────────┘")
    lines.append("```")
    lines.append("")
    lines.append("## Technical Notes")
    lines.append("")
    lines.append("**Primary APIs:**")
    for api in i.primary_apis:
        lines.append(f"- {api}")
    lines.append("")
    lines.append("**Offline Strategy:**")
    lines.append(i.offline_strategy)
    lines.append("")
    lines.append("**Data Handling:**")
    lines.append(i.data_handling)
    lines.append("")
    lines.append("## Competition & Differentiation")
    lines.append("")
    lines.append(f"**Existing Solutions:** {i.competition}")
    lines.append(f"**Our Edge:** {i.edge}")
    lines.append("")
    lines.append("## Development Estimate")
    lines.append("")
    lines.append(f"**Complexity:** {i.complexity}")
    lines.append(f"**Timeline:** {i.timeline}")
    lines.append(f"**Key Challenges:** {i.challenges}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    base = Path("/workspace/landings/ideas")
    if not base.exists():
        raise SystemExit(f"Missing ideas directory: {base}")

    ideas: list[Idea] = [
        Idea(
            id=101,
            folder="09-professional",
            slug="audittrail-forms",
            name="AuditTrail Forms (Offline Field Compliance)",
            category="Professional",
            tier="Pro ($50+)",
            apis="Camera, Files, Local DB, PDF",
            offline="Full",
            one_liner="Offline inspections with tamper-evident evidence packs and audit-ready exports.",
            problem="Field teams fail audits and lose disputes because evidence (photos, signatures, timestamps) is scattered, editable, or missing when offline.",
            solution="A local-first inspection system: build/checklist a form, capture proof (photos, notes, signatures) with a chain-of-custody log, then export a single “audit pack” PDF/ZIP.",
            target_user="Inspectors, safety officers, property managers, contractors doing recurring checks.",
            features=[
                "Template-based form builder (inspection + corrective action)",
                "Evidence capture: photo bundles, annotations, signatures, timestamps",
                "Tamper-evident audit log (hash chain) + completeness score",
                "Report generator: branded PDF + ZIP “audit pack”",
                "Exports: CSV/PDF + secure sharing via Files",
            ],
            model="Subscription",
            price="$9.99/mo (solo) or $59/yr",
            strategy="Free trial for 3 reports; paid unlocks templates, unlimited exports, and audit packs.",
            viz="[Checklist] → [Proof Capture] → [Audit Pack PDF]",
            primary_apis=[
                "Camera: photo evidence + markup",
                "Local database: forms, logs, hashes, reports",
            ],
            offline_strategy="All records stored locally (SQLite). Exports generated on-device; no accounts required.",
            data_handling="Optional biometric lock; local encryption for sensitive projects; no analytics by default.",
            competition="Generic form apps and “field service” suites; many require accounts and cloud sync.",
            edge="Audit-pack workflow + tamper-evident chain-of-custody + offline-first reliability.",
            complexity="High",
            timeline="2-3 weeks",
            challenges="Reliable PDF rendering, evidence hashing UX, data model migrations",
        ),
        Idea(
            id=102,
            folder="02-camera-vision",
            slug="lidar-site-twin-lite",
            name="LiDAR Site Twin Lite",
            category="Camera & Vision",
            tier="Premium ($10-50)",
            apis="LiDAR/AR, Camera, Files, PDF",
            offline="Full",
            one_liner="Quick as-built scans with measurement anchors, issue pins, and contractor-ready exports.",
            problem="Remodelers and inspectors argue over dimensions and site conditions because measurements and photos aren’t captured in a single coherent artifact.",
            solution="Scan a space, drop measurement anchors, attach annotated photos to “issue pins,” then export an as-built packet (floor snapshot + pin list + measurements).",
            target_user="Remodelers, property managers, home inspectors, and real estate professionals.",
            features=[
                "Guided LiDAR scan with confidence/coverage meter",
                "Measurement anchors + reference scale checks",
                "Issue pins with photo + note + severity",
                "As-built export packet (PDF + shareable images)",
                "Project library with offline search",
            ],
            model="One-time",
            price="$24.99",
            strategy="Free “demo scan” mode; pay to export and save unlimited projects.",
            viz="[Scan] → [Pin Issues] → [Export As-Built PDF]",
            primary_apis=[
                "ARKit/LiDAR: depth mesh + measurements",
                "Files: export project packets",
            ],
            offline_strategy="Projects stored locally; exports rendered on-device; no network required.",
            data_handling="No uploads; optional passcode/biometric lock for client projects.",
            competition="Full CAD scanners and cloud-first scanning apps.",
            edge="Fast, lightweight, field-friendly workflow optimized for “good enough” contractor documentation.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="Measurement accuracy UX, LiDAR edge cases, robust export formatting",
        ),
        Idea(
            id=103,
            folder="03-audio-sound",
            slug="noise-compliance-meter",
            name="Noise Compliance Meter Pro",
            category="Audio & Sound",
            tier="Premium ($10-50)",
            apis="Microphone, Local DB, PDF",
            offline="Full",
            one_liner="Calibrated noise logging with standards presets and defensible compliance reports.",
            problem="Venues and worksites get complaints/fines without credible logs that match common noise rules (HOAs, permits, OSHA guidance).",
            solution="Calibrate once, log sessions with metadata, then generate a standards-aligned report showing peaks, averages, and time windows.",
            target_user="Event managers, contractors, building managers, and safety-conscious hobbyists.",
            features=[
                "Calibration workflow + device profile",
                "Session logging with tags (site, permit, activity)",
                "Peak/avg tracking + timeline chart",
                "Standards presets (configurable thresholds)",
                "PDF report + shareable “proof card”",
            ],
            model="One-time",
            price="$14.99",
            strategy="Free meter; paid unlocks logging, presets, and report exports.",
            viz="[Calibrate] → [Log Session] → [Compliance PDF]",
            primary_apis=[
                "Microphone: SPL estimation + filtering",
                "Local database: sessions + metadata",
            ],
            offline_strategy="All logs stored locally; reports generated offline.",
            data_handling="No recordings stored unless user enables “evidence clips.”",
            competition="Generic decibel meters with weak exports and unclear calibration.",
            edge="Standards-first UX + defensible exports + repeatable calibration.",
            complexity="Medium",
            timeline="2 weeks",
            challenges="Calibration UX, device variability, clear reporting",
        ),
        Idea(
            id=104,
            folder="03-audio-sound",
            slug="acoustic-leak-finder",
            name="Acoustic Leak Finder (Guided Sweep)",
            category="Audio & Sound",
            tier="Premium ($10-50)",
            apis="Microphone, DSP/FFT, Haptics",
            offline="Full",
            one_liner="Find air/water leaks by spectral fingerprint with a guided “sweep mode.”",
            problem="Maintenance techs waste hours hunting small leaks; the sound is there, but it’s hard to localize and document.",
            solution="A guided sweep that highlights leak-like frequency bands, gives hotter/colder feedback, and saves an evidence clip + notes.",
            target_user="HVAC techs, plumbers, facility maintenance, DIY homeowners.",
            features=[
                "Sweep mode with real-time spectral heatmap",
                "Leak fingerprints (air vs. water vs. mechanical) presets",
                "Hotter/colder haptic guidance based on signal strength",
                "Evidence clips + photo + notes for handoff",
                "Job history with before/after comparison",
            ],
            model="One-time",
            price="$19.99",
            strategy="App Store SEO for “leak detector”; demo mode limited to 2 saved jobs.",
            viz="[Sweep] → [Lock Target] → [Save Proof]",
            primary_apis=[
                "Microphone: high-sample audio input",
                "Haptics: feedback cues",
            ],
            offline_strategy="On-device DSP; all jobs stored locally with optional export.",
            data_handling="Audio clips stay on device; user-controlled retention policy.",
            competition="Hardware detectors and generic spectrum analyzers.",
            edge="Task-specific UX + leak presets + guided sweep workflow.",
            complexity="High",
            timeline="3 weeks",
            challenges="DSP tuning, device mic differences, false positives",
        ),
        Idea(
            id=105,
            folder="09-professional",
            slug="shift-handover-recorder",
            name="Shift Handover Recorder (Structured)",
            category="Professional",
            tier="Premium ($10-50)",
            apis="Microphone, On-device transcription, Local DB, PDF",
            offline="Full",
            one_liner="Turn end-of-shift brain dumps into structured handovers that don’t miss critical context.",
            problem="Shift workers lose context between handovers, causing errors, stress, and rework—especially when handovers are rushed.",
            solution="Record a quick handover, auto-structure it into sections (risks, tasks, incidents), then export a clean handover note.",
            target_user="Nurses, facility ops, on-call technicians, security teams.",
            features=[
                "Structured handover templates by role",
                "On-device transcription + sectioning (no cloud)",
                "“Risk highlights” checklist (meds, alarms, blockers)",
                "Shift log timeline + sign-off",
                "Export: PDF/notes + share via Files",
            ],
            model="Subscription",
            price="$5.99/mo or $39/yr",
            strategy="Free for 3 handovers/week; paid unlocks unlimited and specialty templates.",
            viz="[Record] → [Structured Note] → [Handover PDF]",
            primary_apis=[
                "Microphone: capture handover audio",
                "Local database: transcripts, tags, logs",
            ],
            offline_strategy="All transcription and storage occurs locally; exports generated offline.",
            data_handling="Encrypted at rest option; biometric lock; no external sharing unless user exports.",
            competition="Generic voice memo apps and team tools requiring accounts.",
            edge="Role-specific structure + safety checklist + offline privacy.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="On-device transcription integration, UX for fast capture, export formatting",
        ),
        Idea(
            id=106,
            folder="09-professional",
            slug="haccp-logbook",
            name="Kitchen HACCP Logbook",
            category="Professional",
            tier="Pro ($50+)",
            apis="Camera, Local DB, Notifications, PDF",
            offline="Full",
            one_liner="Offline food-safety logs with photo proof, corrective actions, and inspection-ready exports.",
            problem="Small kitchens fail inspections because critical control point logs are inconsistent, lost, or not tied to proof.",
            solution="Guided HACCP checks (temps, cleaning, storage) with photo evidence and corrective action records, exported as a single audit packet.",
            target_user="Independent restaurants, food trucks, commissary kitchens.",
            features=[
                "HACCP templates + customizable checkpoints",
                "Scheduled reminders + missed-check escalation",
                "Photo proof + notes per check",
                "Corrective action workflow + accountability",
                "PDF audit pack export (daily/weekly/monthly)",
            ],
            model="Subscription",
            price="$12.99/mo or $79/yr",
            strategy="Free trial; paid unlocks audit packs and multiple locations.",
            viz="[Prompt] → [Capture Proof] → [Audit Pack]",
            primary_apis=[
                "Notifications: scheduled checks",
                "Camera: proof capture",
            ],
            offline_strategy="All logs stored locally; exports generated offline.",
            data_handling="Optional passcode lock; export only on user action.",
            competition="Enterprise kitchen systems requiring cloud accounts.",
            edge="Offline-first + inspection-aligned exports + corrective action rigor.",
            complexity="Medium",
            timeline="2-3 weeks",
            challenges="Template design, reminders UX, reporting",
        ),
        Idea(
            id=107,
            folder="05-data-vaults",
            slug="med-reconciliation-vault",
            name="Medication Reconciliation Vault",
            category="Data Vaults",
            tier="Premium ($10-50)",
            apis="Camera (OCR), Local encryption, Files, PDF",
            offline="Full",
            one_liner="An encrypted med list that prevents dangerous mismatches—appointment-ready in one tap.",
            problem="People arrive to care with incomplete or outdated medication lists, creating safety risks and wasted time.",
            solution="Scan bottles, normalize doses, and maintain a clean timeline; generate a clinician-friendly summary PDF.",
            target_user="Patients with chronic conditions, caregivers, older adults managing multiple meds.",
            features=[
                "Bottle scan + manual correction workflow",
                "Dose normalization + schedule builder",
                "Medication timeline + “recent changes” view",
                "Allergy + reaction notes section",
                "Export appointment packet (PDF)",
            ],
            model="One-time",
            price="$19.99",
            strategy="Free for 3 meds; pay to unlock unlimited meds + exports.",
            viz="[Scan] → [Clean List] → [Appointment PDF]",
            primary_apis=[
                "Camera/OCR: text capture from labels",
                "Local encryption: protect health data",
            ],
            offline_strategy="Encrypted local store; exports generated offline.",
            data_handling="Health data stays on-device; biometric lock optional.",
            competition="General health apps requiring accounts or cloud sync.",
            edge="Reconciliation-centric UX + export quality + local privacy.",
            complexity="High",
            timeline="3 weeks",
            challenges="OCR accuracy on labels, normalization UX, secure storage",
        ),
        Idea(
            id=108,
            folder="16-security",
            slug="personal-evidence-locker",
            name="Personal Evidence Locker",
            category="Security",
            tier="Premium ($10-50)",
            apis="Camera, Microphone, Local encryption, Files, Biometrics",
            offline="Full",
            one_liner="Capture incidents with tamper-evident timestamps and export a single evidence packet.",
            problem="In disputes (landlord, workplace, insurance), evidence is scattered and credibility is questioned.",
            solution="Bundle photos, audio, and notes into locked incident entries with hash-chained logs, then export an evidence packet.",
            target_user="Tenants, caregivers, gig workers, anyone needing documentation for disputes.",
            features=[
                "Incident capture: photo/audio/note bundles",
                "Tamper-evident timeline (hash chain)",
                "Witness/contact notes + optional signatures",
                "Export “evidence packet” (PDF + attachments ZIP)",
                "Biometric lock + panic “hide mode”",
            ],
            model="One-time",
            price="$24.99",
            strategy="Free capture for 1 incident; pay to unlock unlimited incidents and exports.",
            viz="[Capture] → [Lock] → [Export Packet]",
            primary_apis=[
                "Biometrics: secure access",
                "Files: export packet",
            ],
            offline_strategy="Encrypted local storage; exports generated offline.",
            data_handling="No cloud; user controls exports; optional auto-delete policy.",
            competition="Notes apps, generic vaults, cloud evidence services.",
            edge="Court/insurance-style packet generator + provenance logging.",
            complexity="High",
            timeline="3 weeks",
            challenges="Secure encryption UX, export integrity, “hide mode” safety",
        ),
        Idea(
            id=109,
            folder="09-professional",
            slug="inventory-reconciler",
            name="Offline Inventory Reconciler (Barcode + Batches)",
            category="Professional",
            tier="Pro ($50+)",
            apis="Camera (barcode), Local DB, Files, CSV",
            offline="Full",
            one_liner="Fast stocktakes with batch rules, discrepancy audits, and cycle-count plans—offline.",
            problem="Small warehouses and sellers lose money due to Excel-based stocktakes with poor auditability and frequent scanning mistakes.",
            solution="Scan SKUs, count by batch/location, auto-flag discrepancies, and export reconciliation reports that are easy to act on.",
            target_user="Shop owners, resellers, small warehouses, backroom retail managers.",
            features=[
                "Barcode scan + manual SKU fallback",
                "Batch/location counting mode (cycle counts)",
                "Discrepancy engine (expected vs actual)",
                "Audit trail of who/when counted",
                "Exports: CSV + printable discrepancy sheets",
            ],
            model="One-time",
            price="$59.99",
            strategy="Paid from day one; strong value framing vs. shrink and time.",
            viz="[Scan] → [Count] → [Discrepancy Report]",
            primary_apis=[
                "Camera: barcode scanning",
                "Local database: SKU catalog + counts",
            ],
            offline_strategy="Local SKU catalog + counts; import/export via CSV.",
            data_handling="No accounts; optional encrypted catalog if sensitive.",
            competition="Cloud inventory suites, generic barcode apps.",
            edge="Reconciliation logic + auditability + offline reliability.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="Ergonomic scanning UX, reconciliation edge cases, CSV compatibility",
        ),
        Idea(
            id=110,
            folder="09-professional",
            slug="tool-calibration-notebook",
            name="Tool Calibration Notebook",
            category="Professional",
            tier="Pro ($50+)",
            apis="Camera, Local DB, Notifications, PDF",
            offline="Full",
            one_liner="Calibration schedules, evidence photos, and certificates—built for audits.",
            problem="Shops fail QA audits because calibration records are incomplete, inconsistent, or lost across paper binders.",
            solution="Track tools, calibration dates, procedures, and evidence. Generate certificates and audit packs on demand.",
            target_user="Machine shops, labs, manufacturing QA, serious hobby workshops.",
            features=[
                "Asset registry with serials and photos",
                "Calibration schedule + due reminders",
                "Procedure checklists + evidence attachments",
                "Certificate generator (PDF)",
                "Audit pack export by date range",
            ],
            model="Subscription",
            price="$8.99/mo or $59/yr",
            strategy="Free for 5 tools; paid unlocks unlimited tools + certificate exports.",
            viz="[Tool] → [Calibration Entry] → [Certificate PDF]",
            primary_apis=[
                "Notifications: due reminders",
                "Camera: evidence capture",
            ],
            offline_strategy="All records local; exports generated offline.",
            data_handling="Local-only; optional device-level encryption + biometric lock.",
            competition="Spreadsheets and enterprise calibration systems.",
            edge="Audit-first UX + certificate generator + offline simplicity.",
            complexity="Medium",
            timeline="2-3 weeks",
            challenges="Certificate templates, reminder UX, data migrations",
        ),
        Idea(
            id=111,
            folder="09-professional",
            slug="change-order-capture",
            name="Contractor Change-Order Capture",
            category="Professional",
            tier="Premium ($10-50)",
            apis="Camera, Signature, Local DB, PDF",
            offline="Full",
            one_liner="Turn “can you also…” into signed, priced change orders—on site, offline.",
            problem="Contractors lose profit to undocumented scope creep and verbal agreements.",
            solution="Create a change order with photos, line items, and signature, then export a clean PDF for client records.",
            target_user="Contractors, handymen, small service businesses.",
            features=[
                "Change-order templates by trade",
                "Photo proof + markup",
                "Line items + tax/discount presets",
                "On-device signature capture",
                "PDF export + job archive",
            ],
            model="One-time",
            price="$29.99",
            strategy="App Store keywords + partnerships with contractor creators.",
            viz="[Photos] → [Line Items] → [Sign + PDF]",
            primary_apis=[
                "Signature capture: approve changes",
                "PDF: client-ready documents",
            ],
            offline_strategy="Jobs stored locally; PDFs generated offline.",
            data_handling="No cloud; exports only on user action.",
            competition="General invoicing tools and cloud field-service apps.",
            edge="Best-in-class field UX focused purely on change orders.",
            complexity="Medium",
            timeline="2 weeks",
            challenges="PDF layout, signature/legal wording templates",
        ),
        Idea(
            id=112,
            folder="15-home-life",
            slug="home-condition-baseline",
            name="Home Condition Baseline (Insurance-Grade)",
            category="Home & Life",
            tier="Premium ($10-50)",
            apis="Camera, Local DB, PDF, Files",
            offline="Full",
            one_liner="Guided walkthroughs that create claim-ready “before” baselines with structured photo proof.",
            problem="Insurance disputes and landlord conflicts often hinge on “pre-existing damage,” but most people lack organized baseline proof.",
            solution="A guided room-by-room capture flow that produces a timestamped baseline packet you can export anytime.",
            target_user="Homeowners, renters, landlords, property managers.",
            features=[
                "Room-by-room guided checklist (photos required)",
                "Damage tagging + severity + notes",
                "Timeline view for updates over time",
                "Export baseline packet (PDF + attachments)",
                "Reminders for seasonal updates",
            ],
            model="One-time",
            price="$19.99",
            strategy="Seasonal promotion + App Store “home inventory insurance”.",
            viz="[Walkthrough] → [Tag] → [Baseline Packet]",
            primary_apis=[
                "Camera: guided evidence capture",
                "PDF: claim-ready report",
            ],
            offline_strategy="Local project store; exports generated offline.",
            data_handling="No cloud; optional biometric lock.",
            competition="Home inventory apps and generic photo albums.",
            edge="Guided capture UX + insurer-style packet export.",
            complexity="Medium",
            timeline="2-3 weeks",
            challenges="Guided UX design, export formatting, large photo bundles",
        ),
        Idea(
            id=113,
            folder="09-professional",
            slug="offline-incident-commander",
            name="Offline Incident Commander",
            category="Professional",
            tier="Pro ($50+)",
            apis="Local DB, Timers, Files, PDF",
            offline="Full",
            one_liner="Run incidents and drills with protocol checklists, role assignments, and after-action reports—offline.",
            problem="Under stress, teams miss steps and lose a coherent timeline; many “incident” tools depend on connectivity.",
            solution="Choose a playbook, assign roles, run a timed checklist, log actions, and export an after-action report.",
            target_user="School admins, event ops, small facilities, volunteer orgs.",
            features=[
                "Incident playbooks + drill mode",
                "Role assignments + responsibilities",
                "Timed checklists + action log timeline",
                "After-action report generator (PDF)",
                "Reusable templates + customization",
            ],
            model="One-time",
            price="$79.99",
            strategy="Sell to organizations via direct outreach; App Store for individuals/training.",
            viz="[Playbook] → [Run Checklist] → [After-Action PDF]",
            primary_apis=[
                "Local database: logs + templates",
                "Timers: step timing and escalation",
            ],
            offline_strategy="Everything local; exports generated offline.",
            data_handling="No personal data required; optional passcode lock for logs.",
            competition="Enterprise incident platforms requiring accounts.",
            edge="Offline drillable playbooks + after-action reporting.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="Playbook design, stress-proof UX, export clarity",
        ),
        Idea(
            id=114,
            folder="07-productivity",
            slug="adhd-task-triage",
            name="ADHD Task Triage (Evidence-Based)",
            category="Productivity",
            tier="Premium ($10-50)",
            apis="Local DB, Timers, Notifications",
            offline="Full",
            one_liner="Turn overwhelm into a tiny “next action” queue with timed help and proof-of-progress.",
            problem="ADHD users often fail not from lack of lists, but from inability to triage and start.",
            solution="Capture everything, auto-triage into “next actions,” run tiny timed sprints, and build a visible trail of wins.",
            target_user="Adults with ADHD, students, anyone overwhelmed by task volume.",
            features=[
                "Capture inbox + friction tagging (“stuck because…“)",
                "Triage rules engine (effort, urgency, energy)",
                "Timed “start sprint” with gentle prompts",
                "Progress artifacts (weekly wins card)",
                "Review ritual + backlog pruning",
            ],
            model="One-time",
            price="$14.99",
            strategy="Community launches in ADHD/productivity spaces; strong before/after messaging.",
            viz="[Inbox] → [Next Action] → [Sprint + Win]",
            primary_apis=[
                "Notifications: reminders and sprints",
                "Local database: tasks + rules",
            ],
            offline_strategy="Local-only task store; optional export as CSV.",
            data_handling="No accounts; no analytics by default.",
            competition="To-do apps; most don’t solve triage and start friction.",
            edge="Triage + start engine + emotional progress artifacts.",
            complexity="High",
            timeline="3 weeks",
            challenges="Behavioral UX, rule tuning, avoiding feature creep",
        ),
        Idea(
            id=115,
            folder="10-education",
            slug="speech-practice-studio",
            name="Speech Practice Studio (On-Device Coach)",
            category="Education",
            tier="Premium ($10-50)",
            apis="Microphone, On-device ML, Local DB",
            offline="Full",
            one_liner="Practice talks and get offline feedback on pace, clarity, filler words, and structure.",
            problem="People bomb interviews and presentations because they can’t get feedback safely and privately.",
            solution="Record practice sessions, analyze on-device, and generate a scorecard plus targeted drills.",
            target_user="Job seekers, students, founders, Toastmasters.",
            features=[
                "Recording + auto section markers (intro/body/close)",
                "Pace + pause analysis + filler word count",
                "Clarity checklist + “too fast/too long” flags",
                "Drill library (30–90s exercises)",
                "Progress timeline + shareable scorecard",
            ],
            model="One-time",
            price="$19.99",
            strategy="Free for 3 recordings; paid unlocks unlimited + drills.",
            viz="[Record] → [Scorecard] → [Targeted Drills]",
            primary_apis=[
                "Microphone: session recording",
                "On-device ML: transcription/analysis",
            ],
            offline_strategy="All analysis offline; recordings stored locally.",
            data_handling="No uploads; user controls retention.",
            competition="Cloud transcription tools and generic voice recorders.",
            edge="Private offline coaching + drill-based improvement loop.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="On-device speech analysis, UX for feedback, performance",
        ),
        Idea(
            id=116,
            folder="08-creative",
            slug="rehearsal-evidence",
            name="Music Rehearsal Evidence (Band-Proof)",
            category="Creative",
            tier="Premium ($10-50)",
            apis="Microphone, Files, Local DB",
            offline="Full",
            one_liner="Rehearsal recorder that splits takes, tags mistakes, and exports set reports.",
            problem="Bands waste rehearsal time repeating the wrong sections because sessions aren’t structured or searchable.",
            solution="Record rehearsals, drop quick markers (timing, pitch, arrangement), and export a setlist report for the next session.",
            target_user="Bands, music directors, solo performers practicing sets.",
            features=[
                "Long-form rehearsal recording with markers",
                "Take splitting + setlist tagging",
                "Mistake taxonomy (timing, pitch, lyrics, arrangement)",
                "Session summary + next-actions list",
                "Export: audio clips + PDF session report",
            ],
            model="One-time",
            price="$14.99",
            strategy="App Store targeting “rehearsal recorder”; musician demos.",
            viz="[Record] → [Markers] → [Session Report]",
            primary_apis=[
                "Microphone: long recording sessions",
                "Files: export clips and reports",
            ],
            offline_strategy="All recordings local; exports via Files.",
            data_handling="No cloud; user-managed storage and cleanup.",
            competition="Generic multitrack recorders and voice memo apps.",
            edge="Session intelligence + markers + rehearsal-specific reporting.",
            complexity="Medium",
            timeline="2-3 weeks",
            challenges="Audio file management, marker UX, export pipelines",
        ),
        Idea(
            id=117,
            folder="19-niche-pro",
            slug="pocket-lab-notebook",
            name="Pocket Lab Notebook (GLP-Lite)",
            category="Niche Pro",
            tier="Pro ($50+)",
            apis="Camera, Local encryption, Files, PDF",
            offline="Full",
            one_liner="A lab notebook with immutable entries, attachments, and experiment templates—offline.",
            problem="Students and indie labs struggle with reproducibility and provenance when notes are editable, scattered, or not timestamped.",
            solution="Template-driven experiment entries with attachments and tamper-evident timestamps; export a signed experiment record.",
            target_user="Students, makers, small labs, QA hobbyists.",
            features=[
                "Experiment templates (chemistry, bio, electronics)",
                "Immutable entry mode (append-only logs)",
                "Attachments: photos, files, sketches",
                "Witness notes + sign-off (optional)",
                "Export experiment packet (PDF + attachments)",
            ],
            model="One-time",
            price="$59.99",
            strategy="Academic SEO + student discounts; strong differentiation on provenance.",
            viz="[Template] → [Append Log] → [Export Packet]",
            primary_apis=[
                "Local encryption: protect notebooks",
                "PDF: signed record export",
            ],
            offline_strategy="Encrypted local store; append-only entries; export offline.",
            data_handling="No cloud; optional biometric lock.",
            competition="Notes apps and cloud ELNs.",
            edge="Provenance UX + templates + append-only log design.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="Append-only data model, export integrity, template design",
        ),
        Idea(
            id=118,
            folder="09-professional",
            slug="nfc-asset-passport",
            name="NFC Asset Passport",
            category="Professional",
            tier="Pro ($50+)",
            apis="NFC, Local DB, Files, PDF",
            offline="Full",
            one_liner="Tap tagged assets to view service history, parts, warranty, and status—offline.",
            problem="Maintenance history disappears as tools move across sites; teams waste time repeating work or missing critical service.",
            solution="Bind an NFC tag to an asset, then log service events and parts; tap-to-retrieve history instantly on-site.",
            target_user="Facilities teams, contractors, equipment-heavy small businesses.",
            features=[
                "NFC bind/unbind with safety checks",
                "Service log timeline + parts used",
                "Warranty + purchase doc attachments",
                "Status flags (OK / Needs service / Out of order)",
                "Export service history certificate",
            ],
            model="One-time",
            price="$79.99",
            strategy="Sell as “NFC maintenance log”; bundle with tag recommendations.",
            viz="[Tap Tag] → [History] → [Service Certificate]",
            primary_apis=[
                "NFC: read/write asset IDs",
                "Local database: service history",
            ],
            offline_strategy="All asset data local; exports offline.",
            data_handling="No cloud; tag stores only an ID, not sensitive details.",
            competition="Enterprise CMMS tools requiring accounts.",
            edge="NFC-first workflow + offline speed + simple adoption.",
            complexity="High",
            timeline="3 weeks",
            challenges="NFC edge cases, data model, export formatting",
        ),
        Idea(
            id=119,
            folder="10-education",
            slug="offline-citation-vault",
            name="Offline Research Reader (Citation Vault)",
            category="Education",
            tier="Premium ($10-50)",
            apis="Files, Share Extension, Local DB",
            offline="Full",
            one_liner="Save PDFs/snippets into an offline citation graph with fast quoting and export.",
            problem="Students and writers lose sources and can’t cite quickly, leading to wasted time and weaker work.",
            solution="Import PDFs and snippets via share sheet, annotate highlights, and export citations + quotes in standard formats.",
            target_user="Students, researchers, journalists, long-form writers.",
            features=[
                "Import PDFs + web snippets via Share",
                "Highlight + annotation system",
                "Citation metadata editor + DOI fields",
                "Offline search across quotes and notes",
                "Export: BibTeX/CSV + “quote pack”",
            ],
            model="One-time",
            price="$24.99",
            strategy="App Store “citation manager offline”; student discount promo.",
            viz="[Import] → [Annotate] → [Export Citations]",
            primary_apis=[
                "Share extension: capture sources",
                "Local database: citation graph",
            ],
            offline_strategy="All sources stored locally; exports offline.",
            data_handling="No accounts; optional encrypted vault for sensitive research.",
            competition="Cloud citation managers and PDF readers.",
            edge="Offline-first + citation graph UX + fast quote export.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="PDF parsing, share extension UX, export formats",
        ),
        Idea(
            id=120,
            folder="06-health-body",
            slug="care-plan-tracker",
            name="Care Plan Tracker (Family Ops)",
            category="Health & Body",
            tier="Premium ($10-50)",
            apis="Local DB, Notifications, Files, PDF",
            offline="Full",
            one_liner="Offline care routines with incident notes and appointment-ready summaries.",
            problem="Caregivers can’t remember what happened when; appointments become vague, and care quality suffers.",
            solution="Track routines, symptoms, and incidents, then auto-generate a clean appointment summary packet.",
            target_user="Family caregivers, parents managing therapies, elder care.",
            features=[
                "Routine checklists (meds, exercises, therapies)",
                "Symptom + incident logging with severity",
                "Timeline + correlation hints (simple rules)",
                "Appointment packet generator (PDF)",
                "Reminders + missed-task escalation",
            ],
            model="One-time",
            price="$19.99",
            strategy="Caregiver community outreach + App Store “caregiver log”.",
            viz="[Daily Routine] → [Incidents] → [Appointment Packet]",
            primary_apis=[
                "Notifications: routine reminders",
                "Local database: logs and routines",
            ],
            offline_strategy="All care logs local; exports offline.",
            data_handling="Optional encryption + biometric lock.",
            competition="Generic journaling apps and cloud health platforms.",
            edge="Care workflow + appointment-ready summaries + offline privacy.",
            complexity="Medium",
            timeline="2-3 weeks",
            challenges="Summary generation UX, reminder tuning, data model",
        ),
        Idea(
            id=121,
            folder="06-health-body",
            slug="workout-form-mirror",
            name="Workout Form Mirror (On-Device)",
            category="Health & Body",
            tier="Premium ($10-50)",
            apis="Camera, On-device ML, Local DB",
            offline="Full",
            one_liner="Private form checks and consistency scoring—no video uploads.",
            problem="People get injured or stall due to bad form, but don’t want to upload workout videos or pay ongoing coaching fees.",
            solution="Record a set, analyze posture/angles on-device, then output simple cues and a consistency score over time.",
            target_user="Gym-goers, home fitness users, physiotherapy rehab routines.",
            features=[
                "Set recording + rep segmentation",
                "Angle tracking + range-of-motion scoring",
                "Cue cards for common faults",
                "Progress timeline + “consistency” metric",
                "Privacy-first storage + easy deletion",
            ],
            model="One-time",
            price="$29.99",
            strategy="Sell as privacy-first alternative to cloud fitness apps.",
            viz="[Record Set] → [Form Score] → [Cues + Trend]",
            primary_apis=[
                "Camera: video capture",
                "On-device ML: pose estimation",
            ],
            offline_strategy="All pose analysis on-device; no accounts required.",
            data_handling="Local-only videos; optional automatic cleanup after scoring.",
            competition="Cloud coaching apps and subscription fitness platforms.",
            edge="Offline privacy + clean cues + long-term consistency metric.",
            complexity="High",
            timeline="4-6 weeks",
            challenges="Pose estimation reliability, performance, UX for cues",
        ),
        Idea(
            id=122,
            folder="09-professional",
            slug="pocket-contracts",
            name="Pocket Contracts (Clause Builder + Signature)",
            category="Professional",
            tier="Premium ($10-50)",
            apis="Files, PDF, Signature, Local DB",
            offline="Full",
            one_liner="Build professional agreements from clause blocks—offline, fast, and consistent.",
            problem="Freelancers use risky templates and miss critical clauses, creating disputes and unpaid work.",
            solution="Choose a contract type, assemble clauses via a guided builder, then sign and export a clean PDF.",
            target_user="Freelancers, consultants, small agencies.",
            features=[
                "Contract types (SOW, retainer, NDA, change order)",
                "Clause library with plain-language explanations",
                "Smart fields (names, dates, scope, deliverables)",
                "Signature capture + version history",
                "Export and archive (PDF + editable copy)",
            ],
            model="One-time",
            price="$24.99",
            strategy="Sell industry clause packs (design, dev, video) as add-ons.",
            viz="[Choose Type] → [Assemble Clauses] → [Sign + PDF]",
            primary_apis=[
                "PDF: generate contracts",
                "Local database: clause packs",
            ],
            offline_strategy="All clause logic local; exports offline.",
            data_handling="No cloud; optional vault encryption for contract archives.",
            competition="Web-based contract tools requiring accounts.",
            edge="Offline clause builder + clean UX + consistent outputs.",
            complexity="High",
            timeline="3 weeks",
            challenges="Clause design, PDF generation, legal UX clarity",
        ),
        Idea(
            id=123,
            folder="05-data-vaults",
            slug="warranty-packets",
            name="Receipts to Evidence Packs (Warranty/Returns)",
            category="Data Vaults",
            tier="Premium ($10-50)",
            apis="Camera (OCR), Local DB, Notifications, PDF",
            offline="Full",
            one_liner="Turn receipts + photos into a single return/warranty packet with deadline reminders.",
            problem="People lose receipts, miss return windows, and can’t assemble proof quickly when something breaks.",
            solution="Scan receipts, attach product photos/serials, track deadlines, and export a clean warranty packet.",
            target_user="Consumers, families, small offices buying equipment.",
            features=[
                "Receipt scanning + merchant/date/total extraction",
                "Product profile: serial, model, photos, notes",
                "Return/warranty deadline tracker + reminders",
                "Warranty packet export (PDF + attachments)",
                "Searchable catalog + “what’s expiring” list",
            ],
            model="One-time",
            price="$14.99",
            strategy="App Store SEO + “subscription fatigue” positioning.",
            viz="[Scan] → [Attach Proof] → [Export Packet]",
            primary_apis=[
                "Camera/OCR: receipt capture",
                "Notifications: deadline reminders",
            ],
            offline_strategy="Local-only; exports offline.",
            data_handling="No cloud; optional passcode lock for catalog.",
            competition="Generic receipt scanners and note apps.",
            edge="Return/warranty workflow + packet generator + deadlines.",
            complexity="High",
            timeline="3 weeks",
            challenges="Receipt OCR variability, data model, export formatting",
        ),
        Idea(
            id=124,
            folder="07-productivity",
            slug="decision-ledger",
            name="Offline Meeting Decision Log (Decision Ledger)",
            category="Productivity",
            tier="Premium ($10-50)",
            apis="Local DB, Calendar (optional), Files",
            offline="Full",
            one_liner="Capture decisions and owners in meetings, then auto-build a searchable decision ledger.",
            problem="Teams forget decisions; individuals get blamed; meeting notes don’t surface commitments clearly.",
            solution="A decision-first note flow that extracts “Decision / Owner / Due / Rationale” into a ledger export.",
            target_user="Managers, product leads, freelancers juggling multiple clients.",
            features=[
                "Ultra-fast decision capture (one-hand mode)",
                "Owner + due date + confidence level fields",
                "Decision ledger timeline + filters",
                "Weekly “decision digest” export",
                "Meeting templates + action review ritual",
            ],
            model="One-time",
            price="$19.99",
            strategy="Target productivity communities and App Store “meeting notes decisions”.",
            viz="[Meeting] → [Decision Cards] → [Ledger Digest]",
            primary_apis=[
                "Local database: decisions and metadata",
                "Files: export ledger",
            ],
            offline_strategy="All data local; optional calendar link without sync requirements.",
            data_handling="No accounts; optional encryption for client work.",
            competition="Notes apps and team wikis.",
            edge="Decision-centric UX + ledger outputs + weekly digest ritual.",
            complexity="Medium",
            timeline="2 weeks",
            challenges="Fast capture UX, exports, avoiding feature creep",
        ),
        Idea(
            id=125,
            folder="05-data-vaults",
            slug="emergency-binder",
            name="Emergency Binder Generator",
            category="Data Vaults",
            tier="Premium ($10-50)",
            apis="Files, Camera, Local encryption, PDF",
            offline="Full",
            one_liner="Build an offline “grab-and-go” emergency binder that’s printable and encrypted.",
            problem="In emergencies, families can’t find critical documents, contacts, and plans.",
            solution="Guided intake collects essentials and produces a printable binder plus an encrypted on-device vault.",
            target_user="Families, caregivers, frequent travelers, preparedness-minded users.",
            features=[
                "Guided intake checklist (IDs, meds, contacts, plans)",
                "Document capture + organization by section",
                "Printable binder export (PDF)",
                "Offline quick-search + “critical cards”",
                "Periodic review reminders",
            ],
            model="One-time",
            price="$19.99",
            strategy="Seasonal promotion (storms/fires); partnerships with preparedness creators.",
            viz="[Checklist] → [Vault] → [Printable Binder]",
            primary_apis=[
                "Files: import existing docs",
                "Local encryption: protect sensitive info",
            ],
            offline_strategy="Encrypted local vault; exports generated offline.",
            data_handling="Biometric lock recommended; clear privacy nutrition label.",
            competition="Generic document apps and cloud “family organizer” services.",
            edge="Emergency-first UX + printable binder generator + offline guarantee.",
            complexity="High",
            timeline="3 weeks",
            challenges="Secure storage UX, binder formatting, guided flows",
        ),
        Idea(
            id=126,
            folder="09-professional",
            slug="offline-map-ops",
            name="Offline Map Ops (GPX + Task Layers)",
            category="Professional",
            tier="Premium ($10-50)",
            apis="GPS, Files, Local DB, Maps",
            offline="Full",
            one_liner="Load GPX/GeoJSON and run location-based task checklists entirely offline.",
            problem="Fieldwork breaks when coverage drops; teams can’t reliably run tasks tied to map points.",
            solution="Import layers, cache offline maps, attach tasks to points, and export completion reports.",
            target_user="Surveyors, trail crews, researchers, field techs.",
            features=[
                "Import GPX/GeoJSON/KML layers",
                "Offline map caching + fast search",
                "Task lists per point + photo notes",
                "Completion analytics + revisit list",
                "Export: CSV + GPX with status tags",
            ],
            model="One-time",
            price="$24.99",
            strategy="Market as “offline field checklist maps.”",
            viz="[Import Layer] → [Work Pins] → [Export Report]",
            primary_apis=[
                "GPS: location + track recording",
                "Files: import/export layers",
            ],
            offline_strategy="All layers and tasks stored locally; offline tile cache.",
            data_handling="Location data stays on device; export optional.",
            competition="GIS tools with steep learning curve or cloud dependencies.",
            edge="Task-first UX layered on maps + offline reliability.",
            complexity="High",
            timeline="4-6 weeks",
            challenges="Offline map caching, format compatibility, performance",
        ),
        Idea(
            id=127,
            folder="17-accessibility",
            slug="scripted-calls",
            name="Accessibility Scripted Calls (Speech Support)",
            category="Accessibility",
            tier="Micro ($1-5)",
            apis="Text-to-Speech, Local DB",
            offline="Full",
            one_liner="Prebuilt call scripts and one-tap phrases for anxiety/stutter support—offline.",
            problem="People freeze on calls and avoid necessary conversations (appointments, utilities, work) due to anxiety, stutter, or cognitive load.",
            solution="Choose a call scenario, follow a script, and use one-tap phrases or TTS playback to communicate confidently.",
            target_user="People with speech anxiety, stutterers, neurodivergent users, caregivers.",
            features=[
                "Scenario scripts (doctor, landlord, HR, customer support)",
                "One-tap phraseboard (customizable)",
                "Optional TTS speak-out mode",
                "Call prep checklist + notes",
                "Post-call summary template",
            ],
            model="One-time",
            price="$3.99",
            strategy="Low price, high trust; accessibility community outreach.",
            viz="[Choose Scenario] → [Phraseboard] → [Summary]",
            primary_apis=[
                "TTS: speak phrases if needed",
                "Local database: scripts and custom phrases",
            ],
            offline_strategy="All scripts and phrases stored locally.",
            data_handling="No call recording; notes local-only.",
            competition="Generic AAC apps and note templates.",
            edge="Call-specific scripts + fast phrase UX + low friction.",
            complexity="Medium",
            timeline="1-2 weeks",
            challenges="Great script writing, accessibility UX",
        ),
        Idea(
            id=128,
            folder="09-professional",
            slug="micro-clinic-intake",
            name="Micro-Clinic Intake (Offline)",
            category="Professional",
            tier="Pro ($50+)",
            apis="Forms, Signature, Local encryption, PDF",
            offline="Full",
            one_liner="Patient intake + consent + visit notes for pop-up clinics and outreach—offline.",
            problem="Mobile clinics rely on paper intake, causing delays, missing consent, and lost data.",
            solution="Offline forms + signatures with encrypted storage and a clean visit packet export for later filing.",
            target_user="Pop-up clinics, community health orgs, mobile care providers.",
            features=[
                "Intake forms + consent signatures",
                "Visit notes templates + vitals fields",
                "Encrypted local storage + device lock",
                "Export patient packet (PDF)",
                "Batch export for end-of-day filing",
            ],
            model="Subscription",
            price="$29.99/mo per device",
            strategy="Sell via outreach; compliance + offline reliability as core message.",
            viz="[Intake] → [Consent] → [Visit Packet]",
            primary_apis=[
                "Local encryption: protect sensitive records",
                "Signature capture: consent",
            ],
            offline_strategy="No accounts needed; all records local; batch export.",
            data_handling="Privacy-first: encryption at rest, automatic lock, export on demand.",
            competition="EHR portals and cloud intake tools.",
            edge="Offline-first compliance workflow + fast field UX.",
            complexity="High",
            timeline="4-6 weeks",
            challenges="Sensitive-data UX, templates, export reliability",
        ),
        Idea(
            id=129,
            folder="09-professional",
            slug="fleet-pretrip-inspection",
            name="Fleet Pre-Trip Inspection",
            category="Professional",
            tier="Pro ($50+)",
            apis="Camera, Local DB, PDF, Notifications",
            offline="Full",
            one_liner="Guided pre-trip checks with photo proof and defect escalation—offline.",
            problem="Missed defects cause fines, accidents, and downtime; paper checklists are inconsistent and non-auditable.",
            solution="Run a guided inspection, require photos for critical items, log defects, and export compliant reports.",
            target_user="Small fleets, owner-operators, delivery businesses.",
            features=[
                "Vehicle profiles + checklist templates",
                "Critical-step photo requirements",
                "Defect logging + “out of service” flag",
                "Daily/weekly report export (PDF)",
                "Reminder schedules + missed inspection alerts",
            ],
            model="Subscription",
            price="$9.99/mo per driver",
            strategy="Fleet outreach + App Store “DVIR” keywords.",
            viz="[Inspect] → [Log Defect] → [DVIR PDF]",
            primary_apis=[
                "Camera: photo evidence",
                "Notifications: inspection reminders",
            ],
            offline_strategy="Local-only logs; exports offline.",
            data_handling="No tracking unless enabled; all data device-local.",
            competition="Fleet SaaS systems requiring accounts.",
            edge="Offline DVIR + proof-first workflow + simple adoption.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="Template coverage, export compliance, driver UX",
        ),
        Idea(
            id=130,
            folder="02-camera-vision",
            slug="packaging-dimensioner",
            name="Packaging Dimensioner (AR + Catalog)",
            category="Camera & Vision",
            tier="Premium ($10-50)",
            apis="AR, Camera, Local DB, CSV",
            offline="Full",
            one_liner="Measure boxes fast and keep a reusable catalog to reduce shipping costs.",
            problem="Sellers waste money due to incorrect package dimensions and inconsistent packing choices.",
            solution="AR-measure packages, store common box presets, and export dimensions for shipping workflows.",
            target_user="Online sellers, small warehouses, resellers.",
            features=[
                "AR measurement with confidence indicator",
                "Box catalog with presets and photos",
                "Packing notes per SKU (fits/doesn’t fit)",
                "Dimension exports (CSV)",
                "Quick “best box” suggestions from history",
            ],
            model="One-time",
            price="$14.99",
            strategy="Sell to seller communities; App Store “box measurement” keywords.",
            viz="[Measure] → [Save Preset] → [Export CSV]",
            primary_apis=[
                "AR: distance/size measurement",
                "Local database: box catalog",
            ],
            offline_strategy="All presets stored locally; exports offline.",
            data_handling="No account; no data upload.",
            competition="Generic AR measure apps.",
            edge="Shipping-centric catalog + decision help + reliable exports.",
            complexity="High",
            timeline="3 weeks",
            challenges="Measurement UX, catalog design, CSV compatibility",
        ),
        Idea(
            id=131,
            folder="05-data-vaults",
            slug="photo-evidence-timeline",
            name="Photo Evidence Time Machine",
            category="Data Vaults",
            tier="Premium ($10-50)",
            apis="Photos, Files, Local DB, PDF",
            offline="Full",
            one_liner="Turn any photo set into a coherent timeline narrative with notes and dispute-ready exports.",
            problem="Disputes and claims require clear timelines, but albums are messy and lack context.",
            solution="Import photos, add structured notes, generate a timeline narrative, and export a single packet.",
            target_user="People dealing with insurance claims, renovations, custody/landlord disputes.",
            features=[
                "Import albums + auto chronological grouping",
                "Timeline note templates (what/where/who)",
                "Before/after comparisons + side-by-side",
                "Export narrative packet (PDF + attachments)",
                "Optional tamper-evident hash log",
            ],
            model="One-time",
            price="$19.99",
            strategy="SEO around “photo timeline report” and claims communities.",
            viz="[Import] → [Annotate] → [Timeline Packet]",
            primary_apis=[
                "Photos: import library assets",
                "PDF: narrative report export",
            ],
            offline_strategy="Local-only; exports offline.",
            data_handling="No cloud; user-controlled exports.",
            competition="Photo album apps and generic PDF creators.",
            edge="Narrative timeline exports + dispute-oriented templates.",
            complexity="Medium",
            timeline="2-3 weeks",
            challenges="Photo permissions UX, export formatting, performance",
        ),
        Idea(
            id=132,
            folder="10-education",
            slug="offline-drill-engine",
            name="Offline Skills Drill Engine (Authorable)",
            category="Education",
            tier="Pro ($50+)",
            apis="Local DB, Files",
            offline="Full",
            one_liner="Build adaptive drills (spaced repetition + mastery rules) for any domain—offline.",
            problem="Teachers and coaches need custom training, but generic apps don’t match their curriculum or scoring.",
            solution="An offline drill authoring tool with mastery rules, spaced repetition scheduling, and progress exports.",
            target_user="Tutors, coaches, teachers, self-learners with custom curricula.",
            features=[
                "Drill builder (prompts, answers, rubrics)",
                "Mastery rules + spaced repetition scheduler",
                "Adaptive difficulty based on performance",
                "Progress dashboards + export reports",
                "Import/export drill packs (JSON)",
            ],
            model="One-time",
            price="$79.99",
            strategy="Sell to educators; offer cheaper student “player-only” edition later.",
            viz="[Build Drills] → [Practice] → [Mastery Report]",
            primary_apis=[
                "Local database: drills + performance",
                "Files: import/export drill packs",
            ],
            offline_strategy="Fully local; no accounts.",
            data_handling="No PII required; exports user-controlled.",
            competition="Flashcard apps and LMS systems.",
            edge="Authoring + mastery engine + offline portability.",
            complexity="High",
            timeline="4-6 weeks",
            challenges="Rule engine, authoring UX, pack compatibility",
        ),
        Idea(
            id=133,
            folder="07-productivity",
            slug="self-memory-os",
            name="Personal “SELF” Memory OS (Local-First)",
            category="Productivity",
            tier="Premium ($10-50)",
            apis="Local DB, Files, Search, Encryption",
            offline="Full",
            one_liner="Your private memory graph for decisions, prompts, outcomes, and lessons—no cloud required.",
            problem="People repeat mistakes because their learning isn’t indexed; notes are linear and hard to review.",
            solution="Capture “episodes” (decision + context + outcome), link them into a graph, and run review rituals that surface patterns.",
            target_user="Founders, makers, students, knowledge workers who want compounding learning.",
            features=[
                "Episode capture (context, decision, outcome, lesson)",
                "Linking + tags + lightweight graph view",
                "Review prompts (weekly/monthly retrospective)",
                "Powerful offline search + saved queries",
                "Export: JSON/Markdown for portability",
            ],
            model="One-time",
            price="$29.99",
            strategy="Market as privacy-first alternative to cloud PKM tools.",
            viz="[Capture] → [Link] → [Review Insights]",
            primary_apis=[
                "Search: fast local indexing",
                "Encryption: optional vault",
            ],
            offline_strategy="Local-first database with export/import.",
            data_handling="No analytics by default; optional encryption at rest.",
            competition="Notes apps and cloud PKM tools.",
            edge="Decision/outcome-centric schema + review rituals + graph UX.",
            complexity="High",
            timeline="4 weeks",
            challenges="Graph model UX, search indexing, migrations",
        ),
        Idea(
            id=134,
            folder="16-security",
            slug="document-redactor-pro",
            name="On-Device Document Redactor Pro",
            category="Security",
            tier="Premium ($10-50)",
            apis="Files, OCR/ML, PDF",
            offline="Full",
            one_liner="Redact IDs/addresses locally with verified overlays and permanent PDF exports.",
            problem="People overshare sensitive documents; basic “blur” edits are reversible or inconsistent.",
            solution="Detect likely PII on-device, apply permanent redactions, and export a verifiably redacted PDF.",
            target_user="Anyone sharing leases, IDs, medical docs, financial statements.",
            features=[
                "Import PDF/image docs",
                "On-device PII detection (names, addresses, IDs)",
                "Permanent redaction tool (not blur)",
                "Verification view (what’s removed)",
                "Audit note + export PDF",
            ],
            model="One-time",
            price="$24.99",
            strategy="Target privacy communities and App Store “PDF redaction”.",
            viz="[Import] → [Detect PII] → [Export Redacted PDF]",
            primary_apis=[
                "Files: import documents",
                "PDF: render and export",
            ],
            offline_strategy="All detection and export on-device; no uploads.",
            data_handling="Docs never leave device; clear privacy labeling.",
            competition="Cloud PDF editors and scanner apps.",
            edge="Verified permanent redaction offline.",
            complexity="High",
            timeline="4-6 weeks",
            challenges="PDF text extraction, safe redaction, ML detection tuning",
        ),
        Idea(
            id=135,
            folder="05-data-vaults",
            slug="collector-catalog",
            name="Offline Photo Cataloger (Collectors)",
            category="Data Vaults",
            tier="Premium ($10-50)",
            apis="Camera, Local DB, Files, CSV/PDF",
            offline="Full",
            one_liner="Catalog collections with condition rubrics, provenance notes, and insurance-ready exports.",
            problem="Collectors can’t prove provenance/condition for resale or insurance; spreadsheets are painful and error-prone.",
            solution="Capture items with standardized fields and grading rubrics, then export an inventory packet.",
            target_user="Collectors (cards, coins, tools, instruments), resellers.",
            features=[
                "Item capture with photos + metadata fields",
                "Condition rubric + grading notes",
                "Provenance timeline + purchase details",
                "Search + filters (value, rarity, condition)",
                "Export: inventory PDF + CSV",
            ],
            model="One-time",
            price="$19.99",
            strategy="Sell template packs by category (TCG, coins, tools).",
            viz="[Capture] → [Grade] → [Inventory Export]",
            primary_apis=[
                "Camera: item photos",
                "Local database: catalog",
            ],
            offline_strategy="Local-only catalog; exports offline.",
            data_handling="No cloud; optional encryption.",
            competition="General inventory apps and niche marketplaces.",
            edge="Grading rubrics + provenance + insurance-style exports.",
            complexity="Medium",
            timeline="2-3 weeks",
            challenges="Template design, export formatting, performance with many photos",
        ),
        Idea(
            id=136,
            folder="13-finance",
            slug="receipt-truth-budget",
            name="Budget “Receipt Truth” (Local Rules)",
            category="Finance",
            tier="Premium ($10-50)",
            apis="Camera (OCR), Local DB, CSV",
            offline="Full",
            one_liner="Offline expense tracking that reads line items and learns your categories locally.",
            problem="Manual budgeting fails; generic auto-categorization is wrong; people don’t trust cloud finance apps.",
            solution="Scan receipts, categorize line items via transparent local rules, and export clean monthly summaries.",
            target_user="Budgeters who want privacy and accuracy (YNAB fans, frugal households).",
            features=[
                "Receipt scanning + line-item extraction",
                "Local categorization rules (editable and explainable)",
                "Split transactions by category from one receipt",
                "Monthly summaries + trends",
                "Export: CSV compatible with spreadsheets",
            ],
            model="One-time",
            price="$24.99",
            strategy="Position as privacy-first alternative to cloud budgeting apps.",
            viz="[Scan] → [Split + Categorize] → [Monthly Export]",
            primary_apis=[
                "Camera/OCR: receipt capture",
                "Local database: rules + transactions",
            ],
            offline_strategy="All processing and storage local; exports offline.",
            data_handling="No accounts; no bank connections; user owns data.",
            competition="Budgeting apps with bank sync and subscriptions.",
            edge="Line-item truth + transparent local rules + full privacy.",
            complexity="High",
            timeline="4 weeks",
            challenges="OCR variability, rule UX, data model",
        ),
        Idea(
            id=137,
            folder="15-home-life",
            slug="maintenance-predictor",
            name="Maintenance “Failure Predictor” (Local Logs)",
            category="Home & Life",
            tier="Premium ($10-50)",
            apis="Local DB, Notifications, Files",
            offline="Full",
            one_liner="Tracks maintenance events and predicts failure windows from your history—offline.",
            problem="People forget maintenance until something breaks, causing expensive emergencies and stress.",
            solution="Log maintenance events per asset, then show risk windows based on intervals and local history patterns.",
            target_user="Homeowners, landlords, small shop owners.",
            features=[
                "Asset library (appliances, vehicles, systems)",
                "Maintenance timeline + receipts/photos",
                "Risk meter + predicted next failure window",
                "Reminder schedules + seasonal tasks",
                "Export service history for resale/hand-off",
            ],
            model="One-time",
            price="$19.99",
            strategy="Cross-sell from home maintenance; emphasize “avoid $500 emergencies.”",
            viz="[Log] → [Risk Meter] → [Reminder + Export]",
            primary_apis=[
                "Notifications: reminders",
                "Local database: asset history",
            ],
            offline_strategy="Local-only logs; exports offline.",
            data_handling="No cloud; optional encryption.",
            competition="Basic reminder apps and home maintenance trackers.",
            edge="Risk-window UX + history-based predictions + exportable records.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="Prediction heuristics, asset taxonomy UX, reminders",
        ),
        Idea(
            id=138,
            folder="02-camera-vision",
            slug="photo-to-floorplan",
            name="Offline Photo-to-Floorplan (Lightweight)",
            category="Camera & Vision",
            tier="Premium ($10-50)",
            apis="Camera, AR, Local processing, PDF",
            offline="Full",
            one_liner="Capture rooms and produce a simple floorplan with annotated measurements—offline.",
            problem="Landlords and realtors need quick layouts without paying for full CAD or cloud tools.",
            solution="Guided capture + AR measurements generate a simple plan and a photo-linked measurement sheet.",
            target_user="Realtors, landlords, property managers, remodelers.",
            features=[
                "Guided capture flow (corners, walls, doors)",
                "AR measurement assistance + confidence checks",
                "Simple floorplan generation + labels",
                "Photo-to-wall linking for context",
                "Export: floorplan PDF + images",
            ],
            model="One-time",
            price="$24.99",
            strategy="App Store “floor plan maker offline” keywords.",
            viz="[Capture] → [Plan] → [Export PDF]",
            primary_apis=[
                "AR: measurements",
                "Camera: room capture",
            ],
            offline_strategy="All processing local; exports offline.",
            data_handling="No uploads; optional project lock.",
            competition="Cloud floorplan creators and CAD tools.",
            edge="Lightweight offline workflow + good-enough exports for listings.",
            complexity="High",
            timeline="4-6 weeks",
            challenges="Geometry edge cases, measurement UX, export quality",
        ),
        Idea(
            id=139,
            folder="06-health-body",
            slug="nutrition-protocol-builder",
            name="Offline Nutrition Protocol Builder",
            category="Health & Body",
            tier="Premium ($10-50)",
            apis="Local DB, Files, PDF",
            offline="Full",
            one_liner="Build diet protocols with checklists, symptom tracking, and printable plans—offline.",
            problem="People fail diet experiments because there’s no structure, tracking, or clear summary for what worked.",
            solution="Pick a protocol template, track adherence and symptoms, then export a clean “results report.”",
            target_user="People managing sensitivities, athletes, biohackers, health experimenters.",
            features=[
                "Protocol templates (elimination, macros, timing)",
                "Daily adherence checklist + notes",
                "Symptom tracking + simple correlations",
                "Printable meal-plan outline + shopping prompts",
                "Export results report (PDF)",
            ],
            model="One-time",
            price="$14.99",
            strategy="Sell protocol packs (low FODMAP, athlete cut/bulk) as add-ons.",
            viz="[Protocol] → [Track] → [Results Report]",
            primary_apis=[
                "Local database: logs",
                "PDF: exports",
            ],
            offline_strategy="Local-only tracking and exports.",
            data_handling="No cloud; optional lock.",
            competition="Diet apps focused on databases and subscriptions.",
            edge="Protocol-centric UX + clear experiment reporting.",
            complexity="Medium",
            timeline="2-3 weeks",
            challenges="Correlation UX, template design, avoiding creep",
        ),
        Idea(
            id=140,
            folder="10-education",
            slug="classroom-behavior-log",
            name="Offline Classroom Behavior Log (Teacher-Proof)",
            category="Education",
            tier="Pro ($50+)",
            apis="Local DB, PDF",
            offline="Full",
            one_liner="Fast incident logging that produces parent/admin-ready summaries—offline.",
            problem="Teachers spend hours documenting after the fact; details get lost and reports feel inconsistent.",
            solution="One-tap logging with tags and templates that auto-generates clear summaries and timelines.",
            target_user="Teachers, special education staff, administrators.",
            features=[
                "Ultra-fast incident logging templates",
                "Tag system (behavior, trigger, response, outcome)",
                "Student profiles (minimal fields)",
                "Summary generator (weekly/monthly PDF)",
                "Privacy-first local store + export controls",
            ],
            model="Subscription",
            price="$6.99/mo or $49/yr",
            strategy="Teacher community launches; school license upsell.",
            viz="[Tap Log] → [Timeline] → [Admin Summary PDF]",
            primary_apis=[
                "Local database: incidents",
                "PDF: summary exports",
            ],
            offline_strategy="Local-only; exports offline.",
            data_handling="No cloud; strong privacy defaults; minimal student data stored.",
            competition="School systems and spreadsheets.",
            edge="Speed + consistency + exportable summaries without accounts.",
            complexity="High",
            timeline="3-4 weeks",
            challenges="Privacy UX, templates, export quality",
        ),
        Idea(
            id=141,
            folder="16-security",
            slug="privacy-threat-modeler",
            name="Privacy Threat Modeler (Personal)",
            category="Security",
            tier="Premium ($10-50)",
            apis="Local DB, Files",
            offline="Full",
            one_liner="A guided privacy/security checklist that outputs a tailored plan and tracks completion.",
            problem="People feel unsafe but don’t know what to do next; security advice is overwhelming and generic.",
            solution="Pick a threat profile, get prioritized actions, track completion, and export a personal security plan.",
            target_user="Privacy-conscious users, activists, journalists, everyday people after a scare.",
            features=[
                "Threat profile wizard (risk-based)",
                "Prioritized action plan + rationale",
                "Progress tracking + reminders",
                "Secure notes vault for recovery codes",
                "Export printable “security plan”",
            ],
            model="One-time",
            price="$14.99",
            strategy="Privacy community outreach + App Store “security checklist”.",
            viz="[Profile] → [Plan] → [Progress + Export]",
            primary_apis=[
                "Local database: plan and progress",
                "Files: export plan",
            ],
            offline_strategy="All content and progress local.",
            data_handling="No analytics; optional encryption at rest.",
            competition="Blog posts and generic checklist apps.",
            edge="Risk-based prioritization UX + offline privacy + printable plan.",
            complexity="Medium",
            timeline="2 weeks",
            challenges="Content quality, wizard UX, avoiding false authority",
        ),
        Idea(
            id=142,
            folder="09-professional",
            slug="procurement-binder",
            name="Offline Procurement Binder (Job Packs)",
            category="Professional",
            tier="Pro ($50+)",
            apis="Files, Local DB, Search, PDF",
            offline="Full",
            one_liner="Build job-specific binders (specs, photos, checklists) for sites with no signal.",
            problem="Field teams lose docs on-site; specs and checklists live in email threads and cloud drives that don’t load reliably.",
            solution="Create a “job pack” that bundles all files, notes, and checklists offline, with fast search and export.",
            target_user="Construction PMs, field service, site supervisors.",
            features=[
                "Job pack builder (folders + tags)",
                "Offline full-text search + pinned “critical docs”",
                "Checklists + punch list notes",
                "Photo evidence attached to spec sections",
                "Export job pack archive (ZIP/PDF summary)",
            ],
            model="One-time",
            price="$99.99",
            strategy="Direct outreach to contractors; App Store for individuals.",
            viz="[Assemble Pack] → [Search Offline] → [Export Archive]",
            primary_apis=[
                "Files: import specs/docs",
                "Search: local indexing",
            ],
            offline_strategy="All packs stored locally; optional manual backup export.",
            data_handling="No cloud; optional encryption for sensitive projects.",
            competition="Cloud document tools and generic file managers.",
            edge="Job-pack workflow + offline search + field-friendly UX.",
            complexity="High",
            timeline="4 weeks",
            challenges="Search indexing, file handling, performance",
        ),
        Idea(
            id=143,
            folder="09-professional",
            slug="triage-timer",
            name="Triage Timer (Protocol Decision Support)",
            category="Professional",
            tier="Pro ($50+)",
            apis="Timers, Local DB, Haptics, PDF",
            offline="Full",
            one_liner="Protocol-driven timers and checklists for urgent scenarios—built for stress, offline.",
            problem="Under urgency, people skip steps and lose time; protocol knowledge isn’t operationalized on the device.",
            solution="Choose a protocol, run timed steps with haptic cues, log actions, and export a report for training review.",
            target_user="First responders, trainers, industrial safety leads.",
            features=[
                "Protocol library + authoring tool",
                "Timed step runner with haptic cues",
                "Action logging + timestamps",
                "Drill mode + score summary",
                "Export: after-action report (PDF)",
            ],
            model="Subscription",
            price="$9.99/mo",
            strategy="Sell protocol packs (EMS, industrial, event safety).",
            viz="[Protocol] → [Timed Steps] → [After-Action Report]",
            primary_apis=[
                "Timers: step timing",
                "Haptics: stress-proof cues",
            ],
            offline_strategy="All protocols and logs stored locally.",
            data_handling="No PII required; logs export only by user action.",
            competition="Paper protocols and enterprise training systems.",
            edge="Stress UX + protocol runner + drill scoring.",
            complexity="High",
            timeline="4 weeks",
            challenges="Protocol authoring UX, step runner polish, export",
        ),
        Idea(
            id=144,
            folder="08-creative",
            slug="creator-rights-ledger",
            name="Creator Rights Ledger (Offline)",
            category="Creative",
            tier="Premium ($10-50)",
            apis="Files, Local encryption, PDF",
            offline="Full",
            one_liner="Track creations, licenses, collaborators, and proof in a private offline ledger.",
            problem="Creators struggle to prove ownership/terms later because drafts, dates, and agreements are scattered.",
            solution="Record each creation with attachments and rights metadata, then export a “rights packet” for disputes or licensing.",
            target_user="Designers, musicians, writers, photographers, indie creators.",
            features=[
                "Creation entries with attachments (drafts, stems, exports)",
                "License terms + collaborator roles",
                "Milestone timeline + provenance notes",
                "Export rights packet (PDF + attachments)",
                "Encrypted vault + biometric lock",
            ],
            model="One-time",
            price="$19.99",
            strategy="Creator communities; emphasize privacy and provenance.",
            viz="[Create Entry] → [Attach Drafts] → [Export Rights Packet]",
            primary_apis=[
                "Files: import attachments",
                "Local encryption: protect ledger",
            ],
            offline_strategy="Encrypted local ledger; exports offline.",
            data_handling="No cloud; user-controlled exports only.",
            competition="Generic cloud storage and note apps.",
            edge="Rights-first schema + export packets + provenance UX.",
            complexity="High",
            timeline="3 weeks",
            challenges="Schema design, export formatting, secure storage UX",
        ),
    ]

    expected = set(range(101, 145))
    present = {i.id for i in ideas}
    missing = sorted(expected - present)
    if missing:
        raise SystemExit(f"Missing idea definitions for IDs: {missing}")

    written: list[Path] = []
    for i in ideas:
        folder = base / i.folder
        if not folder.exists():
            raise SystemExit(f"Missing folder: {folder}")

        path = folder / f"{i.id:03d}-{i.slug}.md"
        if path.exists():
            raise SystemExit(f"Refusing to overwrite existing file: {path}")

        path.write_text(render_md(i), encoding="utf-8")
        written.append(path)

    print(f"Wrote {len(written)} files:")
    for p in written:
        print(f"- {p}")


if __name__ == "__main__":
    main()

